version: '3.7'
services:
  web:
    container_name: MBProApp
    restart: always
    volumes:
      - .:/
    command: npm start
    ports:
      - "4002:8080"
    environment:
      NODE_ENV: production